# Generated by Django 5.0.4 on 2024-04-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_name_userdetail_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
