# Generated by Django 5.0.4 on 2024-04-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userdetail_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='alien_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='application_type_initial_permission',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='application_type_renewal',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='application_type_replacement',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='apt_ste_flr_physical',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='arrested_or_convicted',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='city_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='city_or_town_physical',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='country_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='country_of_passport',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='current_immigration_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='date_of_last_arrival',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='eligibility_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='employer_e_verify_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='employer_name_e_verify',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='employment_based_categories',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='family_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='form_i94_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='given_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='immigration_status_at_arrival',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='passport_expiration_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='place_of_last_arrival',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='sevis_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='special_filing_instructions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='state_physical',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='state_province_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='stem_opt_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='travel_document_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='uscis_account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='uscis_online_account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='zip_code_physical',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
