# Generated by Django 5.0.4 on 2024-04-07 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_name_remove_userdetail_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='apt_ste_flr_physical',
            new_name='apt_ste_flr',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='city_or_town_physical',
            new_name='city_or_town',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='application_type_initial_permission',
            new_name='consent_for_ssa_disclosure',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='state_physical',
            new_name='countries_of_citizenship1',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='application_type_renewal',
            new_name='has_previously_filed_i765',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='application_type_replacement',
            new_name='has_ssa_card',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='zip_code_physical',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='countries_of_citizenship2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='father_family_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='father_given_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='h1b_spouse_i797_receipt_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='i140_receipt_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='in_care_of_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='is_physical_same_as_mailing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='mother_family_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='mother_given_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='physical_apt_ste_flr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='physical_city_or_town',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='physical_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='physical_street_number_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='physical_zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='ssn',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='street_number_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='wants_ssa_card',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='arrested_or_convicted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='date_of_last_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='passport_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='special_filing_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_permission', models.BooleanField(default=False)),
                ('replacement', models.BooleanField(default=False)),
                ('renewal', models.BooleanField(default=False)),
                ('user_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_type', to='myapp.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='OtherName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(blank=True, max_length=100)),
                ('given_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_names', to='myapp.userdetail')),
            ],
        ),
    ]
