# Generated by Django 5.0.4 on 2024-04-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_apt_ste_flr_physical_userdetail_apt_ste_flr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othername',
            name='user_detail',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='arrested_or_convicted',
            new_name='al_permission',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='arrested_or_convicted_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='arrested_or_convicted_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='other_names_family_name_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='other_names_family_name_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='other_names_family_name_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='other_names_given_name_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='other_names_given_name_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='other_names_given_name_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='other_names_middle_name_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='other_names_middle_name_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='other_names_middle_name_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='replacement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='consent_for_ssa_disclosure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='has_previously_filed_i765',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='has_ssa_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='physical_zip_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='special_filing_instructions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='ssn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='wants_ssa_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='ApplicationType',
        ),
        migrations.DeleteModel(
            name='OtherName',
        ),
    ]
