# Generated by Django 5.0.4 on 2024-04-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userdetail_delete_userdetailfinal'),
    ]

    operations = [
    ]
