from django.db import models

class UserDetail(models.Model):
    username = models.CharField(max_length=150, unique=True)
    al_permission = models.BooleanField(default=False)
    replacement = models.BooleanField(default=False)
    renewal = models.BooleanField(default=False)
    family_name = models.CharField(max_length=100, blank=True)
    given_name = models.CharField(max_length=100, blank=True)
    middle_name = models.CharField(max_length=100, blank=True)
    other_names_family_name_1 = models.CharField(max_length=100, blank=True)
    other_names_given_name_1 = models.CharField(max_length=100, blank=True)
    other_names_middle_name_1 = models.CharField(max_length=100, blank=True)
    other_names_family_name_2 = models.CharField(max_length=100, blank=True)
    other_names_given_name_2 = models.CharField(max_length=100, blank=True)
    other_names_middle_name_2 = models.CharField(max_length=100, blank=True)
    other_names_family_name_3 = models.CharField(max_length=100, blank=True)
    other_names_given_name_3 = models.CharField(max_length=100, blank=True)
    other_names_middle_name_3 = models.CharField(max_length=100, blank=True)
    in_care_of_name = models.CharField(max_length=100, blank=True)
    street_number_name = models.CharField(max_length=100, blank=True)
    apt_ste_flr = models.CharField(max_length=100, blank=True)
    city_or_town = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    zip_code = models.CharField(max_length=100, blank=True)
    is_physical_same_as_mailing = models.BooleanField(default=True)
    physical_street_number_name = models.CharField(max_length=100, blank=True)
    physical_apt_ste_flr = models.CharField(max_length=100, blank=True)
    physical_city_or_town = models.CharField(max_length=100, blank=True)
    physical_state = models.CharField(max_length=100, blank=True)
    physical_zip_code = models.CharField(max_length=100, blank=True)
    alien_registration_number = models.CharField(max_length=100, blank=True)
    uscis_account_number = models.CharField(max_length=100, blank=True)
    has_previously_filed_i765 = models.CharField(max_length=100, blank=True)
    has_ssa_card = models.BooleanField(default=False)
    ssn = models.CharField(max_length=100, blank=True)
    wants_ssa_card = models.BooleanField(default=False)
    consent_for_ssa_disclosure = models.BooleanField(default=False)
    father_family_name = models.CharField(max_length=100, blank=True)
    father_given_name = models.CharField(max_length=100, blank=True)
    mother_family_name = models.CharField(max_length=100, blank=True)
    mother_given_name = models.CharField(max_length=100, blank=True)
    countries_of_citizenship1 = models.CharField(max_length=100, blank=True)
    countries_of_citizenship2 = models.CharField(max_length=100, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    country_of_birth = models.CharField(max_length=100, blank=True)
    city_of_birth = models.CharField(max_length=100, blank=True)
    state_province_of_birth = models.CharField(max_length=100, blank=True)
    immigration_status_at_arrival = models.CharField(max_length=100, blank=True)
    current_immigration_status = models.CharField(max_length=100, blank=True)
    sevis_number = models.CharField(max_length=100, blank=True)
    employer_name_e_verify = models.CharField(max_length=100, blank=True)
    employer_e_verify_id = models.CharField(max_length=100, blank=True)
    eligibility_category = models.CharField(max_length=100, blank=True)
    travel_document_number = models.CharField(max_length=100, blank=True)
    form_i94_number = models.CharField(max_length=100, blank=True)
    place_of_last_arrival = models.CharField(max_length=100, blank=True)
    date_of_last_arrival = models.DateField(null=True, blank=True)  # Consider changing to DateField
    country_of_passport = models.CharField(max_length=100, blank=True)
    passport_expiration_date = models.DateField(null=True, blank=True)  # Consider changing to DateField
    passport_number = models.CharField(max_length=100, blank=True)
    stem_opt_category = models.CharField(max_length=100, blank=True)
    arrested_or_convicted_1 = models.BooleanField(default=False)
    arrested_or_convicted_2 = models.BooleanField(default=False)
    special_filing_instructions = models.CharField(max_length=255, blank=True)
    employment_based_categories = models.CharField(max_length=100, blank=True)
    uscis_online_account_number = models.CharField(max_length=100, blank=True)
    gender = models.CharField(max_length=50, blank=True)
    marital_status = models.CharField(max_length=50, blank=True)
    degree = models.CharField(max_length=100, blank=True)
    h1b_spouse_i797_receipt_number = models.CharField(max_length=100, blank=True)
    i140_receipt_number = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f"{self.family_name} {self.given_name}"
